#!/bin/sh
export DB_HOST=""
export DB_PORT=""
export DB_USER=""
export DB_PASSWORD=""
export DB_DATABASE=""
export DB_CONNECT_TIMEOUT=""
export AUTH0_SECRET=""
export AUTH0_BASE_URL=""
export AUTH0_CLIENT_ID=""
export AUTH0_ISSUER_BASE_URL=""